---
driver:
  name: ssh

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver:
      hostname: kitchen.megam.co
      username: root
      password: $KITCHEN_PASSWORD

suites:
  - name: default
    run_list:
      - recipe[megam_akka::default]
    attributes:
