 ---
driver:
  name: ssh

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver:
      hostname: 144.76.244.46
      username: root
      password: $KITCHEN_PASSWORD

suites:
  - name: megam_java
    run_list:
    - recipe[megam_java]
    attributes:

